language: ruby
rvm:
  - 2.6.4
#sudo: false

cache: bundler

branches:
  only:
  - master

before_script:
  - chmod -R +x scripts/

script: 
  - ./scripts/build.sh

deploy:
  provider: script
  skip-cleanup: true
  script: 
    - ./scripts/deploy.sh
  on:
    branch: master