name: Jekyll

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6.x'
    - uses: actions/cache@v1
      id: pipcache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - uses: actions/cache@v1
      id: gemcache
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    
    # Pre-build
    - name: Install Bundler
      run: |
        gem install bundler -v '2.0.2'
    
    - name: Install Dependencies
      if: steps.gemcache.outputs.cache-hit != 'true'
      run: |
        bundle install --deployment
    
    - name: Install Python Dependencies
      if: steps.pipcache.outputs.cache-hit != 'true'
      run: |
        pip install -r requirements.txt --user

    - name: Compile Jupyter Notebooks
      run: |
        jupyter nbconvert --to html --template jupyter.tpl notebooks/*.ipynb
    
    # Build
    - name: Build
      run: |
        export PATH=`pwd`/vendor/bundle/ruby/2.6.0/bin:$PATH
        export GEM_PATH=`pwd`/vendor/bundle/ruby/2.6.0:$GEM_PATH
        export GEM_HOME=`pwd`/vendor/bundle/ruby/2.6.0:$GEM_HOME
        JEKYLL_ENV=production bundle exec jekyll build --destination site
    
    # Deploy to GH Pages
    - name: Deploy
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "Github Actions"
        cd site
        git init
        git add .
        git commit --quiet -m ":rocket: Deploy to Github Pages"
        git push --force --quiet "https://nmcardoso:${{ secrets.IAGML_GH_ACTIONS_TOKEN }}@github.com/iagml/iagml.github.io.git" master:master
        
